/*
 * JXDatePickerDemoPanel.java
 *
 * Created on April 16, 2005, 9:33 AM
 */

package org.jdesktop.demo.swingx_dev;

import org.jdesktop.demo.DemoPanel;

/**
 * Demonstrates the JXDatePicker component.
 *
 * @author  rbair
 */
public class JXDatePickerDemoPanel extends DemoPanel {
    
    /**
     * Creates new form JXDatePickerDemoPanel 
     */
    public JXDatePickerDemoPanel() {
        setName("Date Picker Demo");
        initComponents();
    }

    public String getHtmlDescription() {
        return "<html>Demonstrates the drop-down date selection component. To " +
                "pick a date from a drop-down calendar, click on the expansion " +
                "arrow to the right of the drop-down. The &quot;current&quot; " +
                "date in the calendar is the date currently in the text field. " +
                "Pick a date!</html>";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();

        setLayout(new java.awt.GridBagLayout());

        add(jXDatePicker1, new java.awt.GridBagConstraints());

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables
    
}
